apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-calculator
  labels:
    app: tip-calculator
spec:
  replicas: 2  # Specify the number of replicas
  selector:
    matchLabels:
      app: tip-calculator
  template:
    metadata:
      labels:
        app: tip-calculator
    spec:
      containers:
        - name: tip-calculator
          image: tipcontainer.azurecr.io/deepaktipcalculator:latest  # Replace with the actual image
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
           
    
