# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: tip-calculator
  labels:
    app: tip-calculator
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: tip-calculator
  type: ClusterIP